// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgvdWH0AGp3iTKQCA89FSAvKOKjavw45Q',
    appId: '1:271105678059:web:74c20b9e491cfd03a83cae',
    messagingSenderId: '271105678059',
    projectId: 'test11-267ee',
    authDomain: 'test11-267ee.firebaseapp.com',
    storageBucket: 'test11-267ee.firebasestorage.app',
    measurementId: 'G-LYVMMJB1GF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmHRJ3h5mUHl_KDg-kIu7DVR9LyJ06SNc',
    appId: '1:271105678059:android:f61ae368230705bea83cae',
    messagingSenderId: '271105678059',
    projectId: 'test11-267ee',
    storageBucket: 'test11-267ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7PP5RPc4oiK5A2UiJfhav31xdMqfjCUo',
    appId: '1:271105678059:ios:e6e822c727bb1b78a83cae',
    messagingSenderId: '271105678059',
    projectId: 'test11-267ee',
    storageBucket: 'test11-267ee.firebasestorage.app',
    iosBundleId: 'com.example.miaged',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7PP5RPc4oiK5A2UiJfhav31xdMqfjCUo',
    appId: '1:271105678059:ios:e6e822c727bb1b78a83cae',
    messagingSenderId: '271105678059',
    projectId: 'test11-267ee',
    storageBucket: 'test11-267ee.firebasestorage.app',
    iosBundleId: 'com.example.miaged',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgvdWH0AGp3iTKQCA89FSAvKOKjavw45Q',
    appId: '1:271105678059:web:f203e98fe60bd7bfa83cae',
    messagingSenderId: '271105678059',
    projectId: 'test11-267ee',
    authDomain: 'test11-267ee.firebaseapp.com',
    storageBucket: 'test11-267ee.firebasestorage.app',
    measurementId: 'G-83KLMT2QN9',
  );

}